<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class ProductVariationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productId = Product::all('id');
        DB::table('product_variations')->insert([
            [
                'id_product' => $productId->random()->id,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Đỏ',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Hồng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Hồng cánh sen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Đỏ',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Hồng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Hồng cánh sen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Đỏ',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Hồng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'Hồng cánh sen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Phấn Má Hồng 3CE Màu Pure Cake - Hồng Đào Cực Baby',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Phấn Má Hồng Dior Rouge Blush 219 Rose Montaigne',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'Phấn Má Hồng Dior Rouge Blush 028 Actrice',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],

            [
                'id_product' => $productId->random()->id,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
            [
                'id_product' => $productId->random()->id,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at' => null
            ],
        ]);
    }
}
