<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
class ProductVariationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('product_variations')->insert([
            [
                'id' => 1,
                'id_product' => 1,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 2,
                'id_product' => 1,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 3,
                'id_product' => 1,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 4,
                'id_product' => 2,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 5,
                'id_product' => 2,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 6,
                'id_product' => 2,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 7,
                'id_product' => 3,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 8,
                'id_product' => 3,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 9,
                'id_product' => 3,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 10,
                'id_product' => 4,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 11,
                'id_product' => 4,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 12,
                'id_product' => 4,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 13,
                'id_product' => 5,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 14,
                'id_product' => 5,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 15,
                'id_product' => 5,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 16,
                'id_product' => 6,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 17,
                'id_product' => 6,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 18,
                'id_product' => 6,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 19,
                'id_product' => 7,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 20,
                'id_product' => 7,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 21,
                'id_product' => 7,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 22,
                'id_product' => 8,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 23,
                'id_product' => 8,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 24,
                'id_product' => 8,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 25,
                'id_product' => 9,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 26,
                'id_product' => 9,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 27,
                'id_product' => 9,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 28,
                'id_product' => 10,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 29,
                'id_product' => 10,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 30,
                'id_product' => 10,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 31,
                'id_product' => 11,
                'name' => 'Trắng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 32,
                'id_product' => 11,
                'name' => 'Đen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 33,
                'id_product' => 11,
                'name' => 'Bạc',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 34,
                'id_product' => 12,
                'name' => 'Đỏ',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 35,
                'id_product' => 12,
                'name' => 'Hồng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 36,
                'id_product' => 12,
                'name' => 'Hồng cánh sen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 37,
                'id_product' => 13,
                'name' => 'Đỏ',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 38,
                'id_product' => 13,
                'name' => 'Hồng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 39,
                'id_product' => 13,
                'name' => 'Hồng cánh sen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 40,
                'id_product' => 14,
                'name' => 'Đỏ',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 41,
                'id_product' => 14,
                'name' => 'Hồng',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 42,
                'id_product' => 14,
                'name' => 'Hồng cánh sen',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 43,
                'id_product' => 15,
                'name' => 'Phấn Má Hồng 3CE Màu Pure Cake - Hồng Đào Cực Baby',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 44,
                'id_product' => 16,
                'name' => 'Phấn Má Hồng Dior Rouge Blush 219 Rose Montaigne',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 45,
                'id_product' => 17,
                'name' => 'Phấn Má Hồng Dior Rouge Blush 028 Actrice',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 46,
                'id_product' => 18,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 47,
                'id_product' => 18,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 48,
                'id_product' => 18,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],

            [
                'id' => 49,
                'id_product' => 19,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 50,
                'id_product' => 19,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 51,
                'id_product' => 19,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 52,
                'id_product' => 20,
                'name' => 'S',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 53,
                'id_product' => 20,
                'name' => 'M',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
            [
                'id' => 54,
                'id_product' => 20,
                'name' => 'L',
                'quantity' => 100,
                'price' => 250000,
                'sale_price' => 200000,
                'status' => true,
                'create_date' => '2024-02-23 08:10:00',
                'update_date' => null,
                'image' => 'image.png',
                'created_at' => '2024-02-23 08:10:00',
                'updated_at'=> null
            ],
        ]);
    }
}